name: Auto-add to project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'release-please[bot]' }}
    steps:
      - uses: actions/add-to-project@v2.0.0
        with:
          project-url: https://github.com/users/chenjr0719/projects/1
          github-token: ${{ secrets.PAT }}
